export { default as AdminDashboard } from './AdminDashboard';
export { default as Users } from './Users';
export { default as Staff } from './Staff';
export { default as Hospitals } from './Hospitals';
export { default as Alerts } from './Alerts';
export { default as BedManagement } from './BedManagement';
export { default as BedBookingManagement } from './BedBookingManagement';
export { default as BloodManagement } from './BloodManagement';
export { default as BlockchainVerification } from './BlockchainVerification';
