const mongoose = require('mongoose');

const EmergencyAlertSchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ['blood_shortage', 'bed_shortage', 'equipment_failure', 'mass_casualty', 'critical_patient', 'outbreak', 'other'],
    required: true
  },
  severity: {
    type: String,
    enum: ['low', 'medium', 'high', 'critical'],
    default: 'medium'
  },
  title: {
    type: String,
    required: true
  },
  description: {
    type: String,
    required: true
  },
  hospital: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Hospital'
  },
  affectedBloodGroups: [{
    type: String,
    enum: ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']
  }],
  affectedBedTypes: [{
    type: String
  }],
  status: {
    type: String,
    enum: ['active', 'acknowledged', 'resolved', 'escalated'],
    default: 'active'
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  acknowledgedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  resolvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  acknowledgedAt: Date,
  resolvedAt: Date,
  autoGenerated: {
    type: Boolean,
    default: false
  },
  targetAudience: {
    type: String,
    enum: ['all', 'admin', 'staff', 'users'],
    default: 'all'
  },
  metadata: {
    type: Map,
    of: mongoose.Schema.Types.Mixed
  }
}, {
  timestamps: true
});

// Index for quick lookups
EmergencyAlertSchema.index({ status: 1, severity: 1 });
EmergencyAlertSchema.index({ hospital: 1, status: 1 });
EmergencyAlertSchema.index({ createdAt: -1 });

// Static method to get active alerts count
EmergencyAlertSchema.statics.getActiveAlertCount = async function() {
  return this.countDocuments({ status: { $in: ['active', 'acknowledged'] } });
};

// Static method to get alerts summary
EmergencyAlertSchema.statics.getAlertsSummary = async function() {
  return this.aggregate([
    {
      $match: {
        status: { $in: ['active', 'acknowledged'] }
      }
    },
    {
      $group: {
        _id: { type: '$type', severity: '$severity' },
        count: { $sum: 1 }
      }
    }
  ]);
};

module.exports = mongoose.model('EmergencyAlert', EmergencyAlertSchema);
